workflows:
  ios-workflow:
    name: "iOS Build Workflow"
    environment:
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          brew install cocoapods
          pod install
      - name: Build app
        script: xcodebuild -workspace MyApp.xcworkspace -scheme MyApp -sdk iphoneos -configuration Release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - anrevietson@gmail.com  # Đảm bảo định dạng email đúng

