workflows:
  ios-workflow:
    name: "Build iOS App"
    environment:
      xcode: latest
      node: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install -g cordova
          npm install
      - name: Add iOS platform
        script: |
          cordova platform add ios
      - name: Build iOS app
        script: |
          cordova build ios --release
    artifacts:
      - build/ios/Release-iphoneos/*.ipa
    publishing:
      email:
        recipients:
          - anrevietson@gmail.com
